### ISSUE TITLE
requirements/base.txt waves-core

### ISSUE THREAD

**Issue by ValentinChCloud** [lirmm/waves-demo#2]
Hello,
I tried to reproduce the tutorial from  http://waves.atgc-montpellier.fr/documentation/installation.html,
and I got an issue with the command

```
$ pip install -r requirements.txt
:
:
Collecting waves-core>=1.0.0 (from -r requirements/base.txt (line 41))
  Could not find a version that satisfies the requirement waves-core>=1.0.0 (from -r requirements/base.txt (line 41)) (from versions: )
No matching distribution found for waves-core>=1.0.0 (from -r requirements/base.txt (line 41))
```

**Comment by marcoooo** [comment]
Document has changed, ans not yet reflecting current install procedure. 

I'll push a new version today or tomorrow.

Sorry for the delay.

Marc

**Comment by marcoooo** [comment]
Project has been updated, documentation is now online in http://waves-demo.readthedocs.io/en/latest/
Let me know if everything works now.

Thanks.

**Comment by ValentinChCloud** [comment]
Thanks
It's working now, but 
https://github.com/lirmm/waves-demo/edit/master/docs/installation.rst#L48-L49
should be ../logs
otherwise 
```
ValueError: Unable to configure handler u'daemon_log_file': [Errno 2] No such file or directory: u'/root/waves-demo/logs/daemon.log'
```

And I have a question 
```
(.venv) root@jupyter-1:~/waves-demo/src# ./manage.py waves queue start
(.venv) root@jupyter-1:~/waves-demo/src# started with pid 13576

(.venv) root@jupyter-1:~/waves-demo/src# ./manage.py runserver --settings=waves_demo.settings.development
Performing system checks...

System check identified no issues (0 silenced).
August 24, 2017 - 14:52:22
Django version 1.11.1, using settings 'waves_demo.settings.development'
Starting development server at http://127.0.0.1:8000/
```
How can I change the adresse 127.0.0.1:8000 ?

**Comment by marcoooo** [comment]
I should not have put some relative path in my docs :-). I'll correct this soon.
the logs dir has to be placed at the application root directory. 

You can change the default following instructions here :
 https://docs.djangoproject.com/fr/1.11/ref/django-admin/#runserver

> Be aware that the runserver command is not intended for production environment. 

I can help you setup a Apache server if you want, because it's a little bit tricky.

**Comment by ValentinChCloud** [comment]
That's very kind but our Galaxy server is Nginx, so I have to try it :D

**Comment by marcoooo** [comment]
If you intend to use waves to launch jobs into your galaxy server, I'am afraid you'll find some bugs in the 'service import' procedure, as we did'nt really test it since new waves version is out. (1.1).

If it's urgent and mandatory for you, I'll check and will surely update waves_galaxy project as well.

**Comment by ValentinChCloud** [comment]
Ok, no worries it's not urgent, i'm doing this for next weeks (3-4)

**Comment by marcoooo** [comment]
Hello, I hope everything is going well with waves, I was wondering if you plan to use the API services to communicate with your app ? I am about to deploy by the end of the week a new core-version with few updates on api contract. In case you are using it, I'll do a new version, if not I'll override current v2.

Let me know.
Marc

**Comment by ValentinChCloud** [comment]
Hello, you can override current v2, I will give you a global feedback in october .

**Comment by marcoooo** [comment]
Ok, thank you, next version is due on the 30th of September. I will push on github at this time.

**Comment by marcoooo** [comment]
The new release has been updated with the newly pipy repository dependency.

**Comment by ValentinChCloud** [comment]
Hello.
I tried the basis installation with sqlite default. And for this step : 


"
1.2.1 If you use default database configuration:

        You may login into backoffice (127.0.0.1:8000) with credentials : demo@demo.fr / demodemo
        A sample ‘cp’ service is already given as a starter service template. Running on local server.
"
Error 500 appears

![image](https://user-images.githubusercontent.com/26431997/31429130-72a7cbd8-ae6d-11e7-8076-3bf4d1432f9c.png)

**Comment by marcoooo** [comment]
Hi Vanlentin, I just check out the last version, and I do not have this error. 
Sorry about your problem, I just realized that the installation description is not clear enough :-) Even if you use default database configuration (sqlite), you still need to create DB (In this release, I removed the .sqlite database from repository, in order to help with non-default database configuration ans sample data setup.)

Did you execute the 'migrate' process to create databases structure ?

.venv)[waves_dir]/src/$ ./manage.py migrate

Then load sample data (the ones with the demo user creation)

(.venv)[waves_dir]/src/$ ./manage.py loaddata demo/fixtures/samples/sample_data.json

If you didn't run the database init steps, you might not have any table installed on your machine. Can you check that your waves.sample.sqlite3 file contains tables ?

**Comment by ValentinChCloud** [comment]
It's better :)

```
sqlite> SELECT name FROM sqlite_master WHERE type='table'
   ...> ;
django_migrations
sqlite_sequence
auth_group
auth_group_permissions
authtools_user_groups
authtools_user_user_permissions
django_admin_log
django_content_type
auth_permission
authtools_user
dashboard_userdashboardmodule
wcore_adaptorinitparam
wcore_job
wcore_jobhistory
wcore_jobinput
wcore_joboutput
wcore_servicebinaryfile
wcore_booleanparam
wcore_decimalparam
wcore_fileinput
wcore_integerparam
wcore_listparam
wcore_textparam
wcore_submissionoutput
wcore_runner
wcore_aparam
wcore_submission
wcore_sampledepparam
wcore_fileinputsample
demo_demowavesservice_restricted_client
demo_demowavesservice
demo_servicecategory
demo_servicemeta
easy_thumbnails_source
easy_thumbnails_thumbnail
easy_thumbnails_thumbnaildimensions
jet_bookmark
jet_pinnedapplication
profiles_userprofile
django_session
wcore_repeatedgroup
wcore_submissionexitcode
sqlite> 

```

**Comment by marcoooo** [comment]
Cool, I'll correct the installation doc to tell to create the database even if using the default parameters.

Marc.

**Comment by ValentinChCloud** [comment]
It's me again, is the package wave-galaxy works. I tried : " pip install waves-galaxy"
https://github.com/lirmm/waves-galaxy/edit/master/docs/installation.rst#L17

```
(.venv) root@v-VirtualBox:~/waves-demo/.venv/lib/python2.7/site-packages/waves/wcore# pip install waves-galaxy
The directory '/home/v/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/v/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting waves-galaxy
  Could not find a version that satisfies the requirement waves-galaxy (from versions: )
No matching distribution found for waves-galaxy
```

Otherwise Waves-demo works well, can you give me few tips for integrate a new tool like Galaxy I don't know where I should start.

Valentin

**Comment by marcoooo** [comment]
for your first question, ... sorry, i simply forgot and didn't push waves-galaxy on pypi during last release.  
You should succeed now with : 

``pip install waves-galaxy-adaptors ``

**Comment by marcoooo** [comment]
For your second question, firstly, you should enable the "galaxy adaptor" in your waves configuration : 

in your settings.py simply create (or update) the WAVES_CORE dictionnary with the path to the galaxy class adaptor (here after is the default value, remove elements not needed in your configuration)
```python
WAVES_CORE = {
...
   'ADAPTORS_CLASSES': (
        'waves.wcore.adaptors.shell.SshShellAdaptor',
        'waves.wcore.adaptors.cluster.LocalClusterAdaptor',
        'waves.wcore.adaptors.shell.SshKeyShellAdaptor',
        'waves.wcore.adaptors.shell.LocalShellAdaptor',
        'waves.wcore.adaptors.cluster.SshClusterAdaptor',
        'waves.wcore.adaptors.cluster.SshKeyClusterAdaptor',
    ),
}
```

You can then add the line corresponding to the galaxy adaptor class : 
```python
    'waves.adaptors.galaxy.tool.GalaxyJobAdaptor',
```

So from now, in backoffice, you can create a 'Execution Environment' for this special class, select 'run on' with 'Tool > GalaxyjobAdaptor'
Edit and do 'save and continue editing' to enable the parameters tab. 
That's where you setup configuration to connect to your galaxy instance (you just need api_key, host, protocol - http or https-). leave all other fields blank.

Then create a service running on this 'Execution environment', setup your inputs / expected outputs.
You migth find in your service page a button "add submission from adapter", but unfortunatly, I think it's currently broken. I'll repair the automatic import as soon as possible, do you need this function, or do you already know what your galaxy service is expecting ? In case import fails, please submit an issue in https://github.com/lirmm/waves-galaxy

**Comment by ValentinChCloud** [comment]
Ok I will try that, but first of all is it normal than after

> So from now, in backoffice, you can create a 'Execution Environment' for this special class, select 'run on' with 'Tool > GalaxyjobAdaptor'

I got multiple AutoGenerated Runner from importer, generated punctualy 

![image](https://user-images.githubusercontent.com/26431997/31446077-f034af6c-ae9f-11e7-8dcf-6806c2edc1b8.png)
?

**Comment by marcoooo** [comment]
Well, no, I am afraid introduced a bad bug during last updates on waves-galaxy module. I just created issue in waves-galaxy project. lirmm/waves-galaxy#1

**Comment by marcoooo** [comment]
Ok then I'll try to correct Galaxy import in the next few days. Sorry for the delay. 

By the way I think I will activate 'by default' waves-galaxy-adaptors in waves-demo project. In order to validate process for future releases:). 

I may push on the waves-demo repo soon so.

**Comment by yvanlebras** [comment]
Thanks for your help @marcoooo ! For sure it will be good to activate 'by default' waves-galaxy-adaptors in waves-demo project !

**Comment by marcoooo** [comment]
Hi Yvan, Valentin, I juste released new version of waves-core, waves-galaxy and waves-demo. 

I integrated waves-galaxy inside dependencies for waves-demo. 

I corrected Import, tested with FastME retrieved from our local galaxy instance. 

If you experience more trouble during your test. Don't hesitate to create a new ticket. And if you need updates, you can try to correct and send a PR, I'll be glad to get a little help on this matter !
