### ISSUE TITLE
From documentation

### ISSUE THREAD

**Issue by yvanlebras** [lirmm/waves-demo#3]
`(.venv)[waves_dir//waves-webapp]]$ pip install -r requirements.txt` instead of  `(.venv)[waves_dir]]$ pip install -r requirements.txt` no ?

**Comment by marcoooo** [comment]
thanks for the report :-)
The directory separator is doubled, true, I'll correct this on next push. But anyway you should be able to install dependencies from any directory once you activated the virtualenv.
