### ISSUE TITLE
Error on the Documentation ?

### ISSUE THREAD

**Issue by yvanlebras** [lirmm/waves-demo#4]
On the doc, we can see this `(.venv)[waves_dir]/src/$ cd waves_services/settings` instead of `(.venv)[waves_dir]/src/$ cd waves_demo/settings` no ?

**Comment by marcoooo** [comment]
Yep. I'll correct this on next push as well. thank you.

**Comment by yvanlebras** [comment]
From the doc here : http://waves.atgc-montpellier.fr/documentation/installation.html
Maybe not the updated one ?

**Comment by marcoooo** [comment]
The new version is now on readthedocs :-). I should have removed this one !

http://waves-demo.readthedocs.io/en/latest/index.html

**Comment by yvanlebras** [comment]
Merci ;)
